version: "3.0"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      -  mongodata:/data/db
    networks:
      - portal_vendas_rest_network

  web:
    build: .
    ports:
    - 8081:8081
    depends_on:
    - mongo
    networks:
    - portal_vendas_rest_network

networks:
  portal_vendas_rest_network:
    driver: bridge


volumes:
  mongodata: